services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UBUNTU_VERSION: "20.04"
        FLB_VERSION: v4.2.4
    # For Apple Silicon targeting amd64:
    platform: linux/amd64
    volumes:
      - ./:/workspaces/fluent-bit
    tty: true
    stdin_open: true
